[package]
name = "timed"
version = "0.1.0"
edition = "2021"
description = "Precise timing and performance measurement using tracing"
license = "MIT"
repository = "https://github.com/copiumnicus/timed"

[dependencies]
tracing = "0.1.37"
